server:
  port: 8082

spring:
  application:
    name: provider

eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
