server:
  port: 8081

spring:
  application:
    name: rent-car-service

eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
