server:
  port: 80

spring:
  application:
    name: gateway-80

  cloud:
    gateway:
      enabled: true #开启网关，默认是开启的
      routes: #设置路由，注意是数组，可以设置多个，按照 id 做隔离
        - id: user-service-router #路由 id，没有要求，保持唯一即可
          uri: http://localhost:8081 #设置真正的服务 ip:port
          predicates: #断言匹配
            - Path=/doLogin #和服务中的路径匹配,是正则匹配的模式
        - id: provider-service-router
          uri: http://localhost:8082
          predicates:
            - Path=/info/** #如果匹配到第一个路由，则第二个就不会走了，注意这不是负载均衡

#eureka 的配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
