server:
  port: 8081

mybatis:
  type-aliases-package: com.mu.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    druid:
      test-while-idle: false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud1?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: muzuki

