server:
  port: 8001

spring:
  application:
    name: eureka-client-a

eureka:
  client:
    service-url:  #eureka服务端和客户端的交互地址，集群使用 ',' 来分割
      defaultZone: http://peer1:7001/eureka/
    fetch-registry: true # 拉取服务列表
    register-with-eureka: true # 是否注册自己（集群需要注册自己和拉取服务）

  instance:
    lease-expiration-duration-in-seconds: 30 #eureka客户端向服务端发送心跳时间，每30s发送一次

